### ISSUE TITLE
Address failing Ruff tests

### ISSUE THREAD

**Issue by ukmo-ccbunney** [SciTools/cf-units#526]
```[tasklist]
### Tasks
- [x] `A001` builtin-variable-shadowing
- [ ] `ANN001` missing-type-function-argument
- [ ] `ANN003` missing type annotation for `**kwargs`
- [ ] `ANN201` missing-return-type-undocumented-public-function
- [ ] `ANN202` missing-return-type-private-function
- [ ] `ANN204` missing-return-type-special-method
- [ ] `ANN205` missing-return-type-static-method
- [ ] `ANN206` missing-return-type-class-method
- [ ] `ARG002` Unused method argument
- [ ] `B904` raise-without-from-inside-except
- [ ] `D100` undocumented-public-module
- [ ] `D101` undocumented-public-class
- [ ] `D102` undocumented-public-method
- [ ] `D103` undocumented-public-function
- [ ] `D105` undocumented-magic-method
- [ ] `D205` blank-line-after-summary
- [x] `D301` Use `r"""` if any backslashes in a docstring
- [ ] `D400` ends-in-period (docstring)
- [x] `D401` non-imperative-mood
- [x] `D404` first-line-capitalized
- [ ] `DTZ001` call-datetime-without-tzinfo
- [ ] `DTZ006` call-datetime-fromtimestamp
- [x] `EM101` raw-string-in-exception
- [ ] `EM102` f-string-in-exception
- [ ] `F403` Wildcard imports
- [ ] `F405` Use of name from wildcard import
- [x] `FBT002` boolean-default-value-positional-argument
- [ ] `FIX002` Line contains TODO, consider resolving the issue
- [x] `FLY002` Consider f-string instead of string join
- [ ] `INP001` part of an implicit namespace package. Add an `__init__.py`.
- [ ] `N801` invalid-class-name
- [ ] `N802` invalid-function-name
- [ ] `N803` Argument name should be lowercase
- [ ] `N806` Variable in function should be lowercase
- [ ] `PGH004` Use a colon when specifying `noqa` rule codes
- [ ] `PLC0414` Import alias does not rename original package
- [ ] `PLR0912` Too many branches
- [ ] `PLR0913` too-many-argument
- [ ] `PLR2004` magic-value-comparison
- [ ] `PT006` pytest-parametrize-names-wrong-type
- [ ] `PT011` pytest-raises-too-broad
- [ ] `PT012` pytest-raises-with-multiple-statements
- [ ] `PT019` pytest-fixture-param-without-value
- [ ] `PTH123` builtin-open
- [ ] `RET504` Unnecessary assignment to before statement
- [ ] `RUF001` ambiguous-unicode-character-string
- [ ] `RUF003` ambiguous-unicode-character-comment
- [ ] `RUF012` Mutable class attributes should be annotated with `typing.ClassVar`
- [ ] `S101` Assert used
- [ ] `S102` exec used
- [ ] `S310` Audit URL open for permitted schemes.
- [ ] `S603` subprocess-without-shell-equals-true
- [ ] `S607` start-process-with-partial-path
- [ ] `S701` By default, jinja2 sets `autoescape` to `False`.
- [ ] `SIM108` Use ternary operator instead of `if`-`else`-block
- [ ] `SLF001` private-member-access
- [ ] `T201` `print` found
- [ ] `TD002` Missing author in TODO; try
- [ ] `TD003` Missing issue link on the line following this TODO
- [ ] `TD004` Missing colon in TODO
- [ ] `TRY003` raise-vanilla-args
```
